apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apicast-production-opentrace
  labels:
    app: APIcast
spec:
  paused: true
  replicas: 1
  strategy:
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 1800
      updatePeriodSeconds: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        deployment: apicast-production-opentrace
    spec:
      containers:
      - env:
        - name: APICAST_CONFIGURATION_LOADER
          value: "boot"
        - name: APICAST_CONFIGURATION_CACHE
          value: "300"
        - name: THREESCALE_DEPLOYMENT_ENV
          value: "production"
        - name: BACKEND_ENDPOINT_OVERRIDE
          value: http://backend-listener:3000
        image: 3scale-amp22/apicast-gateway:1.8-5
        imagePullPolicy: IfNotPresent
        name: apicast-production-opentrace
        resources:
          # JA Bride:  Dropping for non-production deployment
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 256m
            memory: 64Mi
        livenessProbe:
          httpGet:
            path: /status/live
            port: 8090
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /status/ready
            port: 8090
          initialDelaySeconds: 15
          timeoutSeconds: 5
          periodSeconds: 30
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8090
          protocol: TCP
  triggers:
  - type: ConfigChange
  - type: ImageChange
    imageChangeParams:
      automatic: true
      containerNames:
      - apicast-production
      from:
        kind: ImageStreamTag
        name: amp-apicast:latest
